//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.TACM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.TACM.Resources.Resources.AccountMessage", typeof(AccountMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác nhận không đúng. Vui lòng nhập lại..
        /// </summary>
        public static string CAPTCHA_INVALID {
            get {
                return ResourceManager.GetString("CAPTCHA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu không thành công..
        /// </summary>
        public static string CHANGE_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        public static string CHANGE_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Xin chào &quot;{0}&quot;!&lt;/b&gt;&lt;br/&gt;&lt;br/&gt;Vui lòng nhập lại mật khẩu mới để cập nhật lại mật khẩu..
        /// </summary>
        public static string CHANGE_TEMP_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_TEMP_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Chào {_Name}&lt;/p&gt;
        ///Bạn vừa chọn chức năng để đặt lại mật khẩu.&lt;br/&gt;
        ///Để đặt lại mật khẩu mới, vui lòng nhấp vào dường dẫn bên dưới:&lt;br/&gt;
        ///http://quanlian.camau.org.vn/datlaimatkhau &lt;br/&gt;
        ///Để xem hướng dẫn đặt lại mật khẩu, vui lòng nhấp vào dường dẫn dưới đây:&lt;br/&gt;
        ///http://quanlian.camau.org.vn/huongdandatlaimatkhau &lt;br/&gt;.
        /// </summary>
        public static string FORGOT_PASSWORD_EMAIL_BODY {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không tồn tại..
        /// </summary>
        public static string FORGOT_PASSWORD_EMAIL_NOT_EXIST {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_EMAIL_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại password để đăng nhập phần mềm Tòa Án Cà Mau..
        /// </summary>
        public static string FORGOT_PASSWORD_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi email không thành công, vui lòng thử lại..
        /// </summary>
        public static string FORGOT_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được gửi tới địa chỉ email của bạn, vui lòng kiểm tra lại email và đăng nhập lại để tiếp tục truy cập vào hệ thống..
        /// </summary>
        public static string FORGOT_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập không thành công..
        /// </summary>
        public static string LOGIN_FAIL {
            get {
                return ResourceManager.GetString("LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công..
        /// </summary>
        public static string LOGIN_SUCCESS {
            get {
                return ResourceManager.GetString("LOGIN_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng. Vui lòng nhập lại..
        /// </summary>
        public static string LOGIN_USER_INVALID {
            get {
                return ResourceManager.GetString("LOGIN_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu đặt lại mật khẩu của bạn không hợp lệ. Vui lòng gửi lại yêu cầu..
        /// </summary>
        public static string RESET_PASSWORD_FAIL {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thành công..
        /// </summary>
        public static string RESET_PASSWORD_SUCCESS {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ủy quyền không hợp lệ. Vui lòng đăng nhập lại..
        /// </summary>
        public static string USER_IS_NULL {
            get {
                return ResourceManager.GetString("USER_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng &quot;{0}&quot; không có đủ quyền truy cập vào trang này &quot;{1}&quot;. Vui lòng liên hệ với quản trị viên để biết thêm thông tin..
        /// </summary>
        public static string USER_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("USER_NOT_AUTHORIZED", resourceCulture);
            }
        }
    }
}
