//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.TACM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.TACM.Resources.Resources.EmailTemplate", typeof(EmailTemplate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Xin chào {_ToaAnNhan_},&lt;/p&gt;
        ///&lt;p&gt;Tòa án vừa nhận được thông báo chuyển đơn từ {_ToaAnChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin của đơn được chuyển đến Tòa án:&lt;/p&gt;
        ///&lt;p&gt;- Mã hồ sơ được chuyển đi: &lt;b&gt;{_MaHoSo_}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;- Ngày chuyển đơn: {_NgayChuyen_}&lt;/p&gt;
        ///&lt;p&gt;- Người chuyển đơn: {_NguoiChuyen_}&lt;/p&gt;
        ///&lt;p&gt;- Lý do chuyển đơn: {_LyDoChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Mong {_ToaAnNhan_} xem xét thông tin của đơn được chuyển đến và thụ lý sơ thẩm tiếp tục.&lt;/p&gt;
        ///&lt;p&gt;Trân t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CHUYENDON_EMAIL_BODY {
            get {
                return ResourceManager.GetString("CHUYENDON_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo chuyển đơn.
        /// </summary>
        public static string CHUYENDON_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CHUYENDON_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Xin chào {_ToaAnNhan_},&lt;/p&gt;
        ///&lt;p&gt;Tòa án vừa nhận được thông báo chuyển hồ sơ từ {_ToaAnChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin của hồ sơ được chuyển đến Tòa án:&lt;/p&gt;
        ///- &lt;p&gt;Mã hồ sơ được chuyển đi: &lt;b&gt;{_MaHoSo_}&lt;/b&gt;&lt;/p&gt;
        ///- &lt;p&gt;Ngày chuyển sơ: {_NgayChuyen_}&lt;/p&gt;
        ///- &lt;p&gt;Người chuyển sơ: {_NguoiChuyen_}&lt;/p&gt;
        ///- &lt;p&gt;Lý do chuyển hồ sơ: {_LyDoChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Mong {_ToaAnNhan_} xem xét thông tin của hồ sơ được chuyển đến và thụ lý sơ thẩm tiếp tục.&lt;/p&gt;
        ///&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CHUYENHOSO_EMAIL_BODY {
            get {
                return ResourceManager.GetString("CHUYENHOSO_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo chuyển hồ sơ.
        /// </summary>
        public static string CHUYENHOSO_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CHUYENHOSO_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Xin chào {_ToaAnNhan_},&lt;/p&gt;
        ///&lt;p&gt;Tòa án vừa nhận được thông báo chuyển hồ sơ từ {_ToaAnChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin của hồ sơ được chuyển đến Tòa án:&lt;/p&gt;
        ///&lt;p&gt;Mã hồ sơ được chuyển đi: &lt;b&gt;{_MaHoSo_}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Ngày chuyển hồ sơ: {_NgayChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Người chuyển hồ sơ: {_NguoiChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Lý do chuyển hồ sơ: {_TruongHopChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Ghi chú: {_GhiChu_}&lt;/p&gt;
        ///&lt;p&gt;Mong {_ToaAnNhan_} xem xét thông tin của hồ sơ được chuyển đến và nh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_EMAIL_BODY {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_EMAIL_FROM {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_EMAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo chuyển hồ sơ phúc thẩm.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_EMAIL_TO {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_EMAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Xin chào {_ToaAnNhan_},&lt;/p&gt;
        ///&lt;p&gt;Tòa án vừa nhận được thông báo chuyển hồ sơ từ {_ToaAnChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin của hồ sơ được chuyển đến Tòa án:&lt;/p&gt;
        ///&lt;p&gt;Mã hồ sơ được chuyển đi: &lt;b&gt;{_MaHoSo_}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Ngày chuyển hồ sơ: {_NgayChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Người chuyển hồ sơ: {_NguoiChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Lý do chuyển hồ sơ: {_TruongHopChuyen_}&lt;/p&gt;
        ///&lt;p&gt;Ghi chú: {_GhiChu_}&lt;/p&gt;
        ///&lt;p&gt;Mong {_ToaAnNhan_} xem xét thông tin của hồ sơ và thụ lý sơ thẩm lại [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_BODY {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_FROM {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo trả hồ sơ phúc thẩm.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_TO {
            get {
                return ResourceManager.GetString("CHUYENHOSOPHUCTHAM_VE_SOTHAM_EMAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Chào {0},&lt;/p&gt;
        ///&lt;p&gt;Bạn vừa được tạo tài khoản cá nhân mới tại hệ thống: {1}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin đăng nhập của bạn:&lt;/p&gt;
        ///&lt;p&gt;Tên đăng nhập:  &lt;b&gt;{2}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Mật khẩu: &lt;b&gt;{3}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Mời bạn đăng nhập theo đường dẫn dưới đây và đổi lại mật khẩu để đảm bảo quyền bảo mật tài khoản của bạn:&lt;/p&gt;
        ///&lt;p&gt;http://qlnvtoaan.camau.gov.vn/&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string NEW_NHANVIEN_EMAIL_BODY {
            get {
                return ResourceManager.GetString("NEW_NHANVIEN_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản nhân viên mới.
        /// </summary>
        public static string NEW_NHANVIEN_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("NEW_NHANVIEN_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Xin chào {_ToaAnNhan_},&lt;/p&gt;
        ///&lt;p&gt;{_ToaAnChuyen_} xin thông báo cho {_ToaAnNhan_} được biết là chúng tôi đã nhận hồ sơ có mã là {_MaHoSo_} để xử phúc thẩm.&lt;/p&gt;
        ///&lt;p&gt;Trân trọng và cảm ơn,&lt;/p&gt;
        ///&lt;p&gt;------------------------&lt;/p&gt;
        ///&lt;p&gt;{_NguoiNhanHoSo_}&lt;/p&gt;
        ///&lt;i&gt;&lt;p&gt;{_ToaAnChuyen_}&lt;/p&gt;&lt;/i&gt;
        ///&lt;i&gt;&lt;p&gt;{_EmailToaAnChuyen_}&lt;/p&gt;&lt;/i&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string NHANHOSOPHUCTHAM_EMAIL_BODY {
            get {
                return ResourceManager.GetString("NHANHOSOPHUCTHAM_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string NHANHOSOPHUCTHAM_EMAIL_FROM {
            get {
                return ResourceManager.GetString("NHANHOSOPHUCTHAM_EMAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo nhận hồ sơ phúc thẩm.
        /// </summary>
        public static string NHANHOSOPHUCTHAM_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("NHANHOSOPHUCTHAM_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;{0}&lt;/p&gt;
        ///&lt;p&gt;{1}&lt;/p&gt;.
        /// </summary>
        public static string NHANHOSOPHUCTHAM_EMAIL_TO {
            get {
                return ResourceManager.GetString("NHANHOSOPHUCTHAM_EMAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password1.
        /// </summary>
        public static string NHANVIEN_DEFAULT_PASSWORD {
            get {
                return ResourceManager.GetString("NHANVIEN_DEFAULT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family: &apos;Times New Roman&apos;;font-size:14pt&quot;&gt;
        ///&lt;p&gt;Chào {0},&lt;/p&gt;
        ///&lt;p&gt;Bạn vừa được sửa mã nhân viên (tên đăng nhập) tại hệ thống: {1}&lt;/p&gt;
        ///&lt;p&gt;Dưới đây là thông tin đăng nhập của bạn:&lt;/p&gt;
        ///&lt;p&gt;Mã nhân viên cũ:  &lt;b&gt;{2}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Mã nhân viên mới: &lt;b&gt;{3}&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Mời bạn đăng nhập theo đường dẫn dưới đây và đổi lại mật khẩu để đảm bảo quyền bảo mật tài khoản của bạn:&lt;/p&gt;
        ///&lt;p&gt;http://qlnvtoaan.camau.gov.vn/&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string SUAMANHANVIEN_EMAIL_BODY {
            get {
                return ResourceManager.GetString("SUAMANHANVIEN_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo mã nhân viên được thay đổi.
        /// </summary>
        public static string SUAMANHANVIEN_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("SUAMANHANVIEN_EMAIL_SUBJECT", resourceCulture);
            }
        }
    }
}
