//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.TACM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifyMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifyMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.TACM.Resources.Resources.NotifyMessage", typeof(NotifyMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa {0} này không?.
        /// </summary>
        public static string BANCO_MUONXOA {
            get {
                return ResourceManager.GetString("BANCO_MUONXOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} bị trùng..
        /// </summary>
        public static string BITRUNG {
            get {
                return ResourceManager.GetString("BITRUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ảnh đại diện thành công..
        /// </summary>
        public static string CAPNHAT_DAIDIEN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("CAPNHAT_DAIDIEN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} không thành công!.
        /// </summary>
        public static string CAPNHAT_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("CAPNHAT_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật {0} thành công!.
        /// </summary>
        public static string CAPNHAT_THANHCONG {
            get {
                return ResourceManager.GetString("CAPNHAT_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp nhận file: XLS, XLSX.
        /// </summary>
        public static string CHAPNHAN_FILE {
            get {
                return ResourceManager.GetString("CHAPNHAN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại chưa có dữ liệu..
        /// </summary>
        public static string CHUACO_DULIEU {
            get {
                return ResourceManager.GetString("CHUACO_DULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh: &quot;{0}&quot; không hợp lệ.
        /// </summary>
        public static string CHUCDANH_KHONGHOPLE {
            get {
                return ResourceManager.GetString("CHUCDANH_KHONGHOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ: &quot;{0}&quot; không hợp lệ.
        /// </summary>
        public static string CHUCVU_KHONGHOPLE {
            get {
                return ResourceManager.GetString("CHUCVU_KHONGHOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DANGXUAT_THANHCONG {
            get {
                return ResourceManager.GetString("DANGXUAT_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] chứa dữ liệu không hợp lệ..
        /// </summary>
        public static string DULIEU_KHONGHOPLE {
            get {
                return ResourceManager.GetString("DULIEU_KHONGHOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ *.PDF, *.DOC, *.DOCX. Dung lượng tối đa 5MB..
        /// </summary>
        public static string DUNGLUONG_FILE_TOIDA {
            get {
                return ResourceManager.GetString("DUNGLUONG_FILE_TOIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng tối đa {0}MB.
        /// </summary>
        public static string DUNGLUONG_TOIDA {
            get {
                return ResourceManager.GetString("DUNGLUONG_TOIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email [{0}] bị trùng..
        /// </summary>
        public static string EMAIL_KHONGBITRUNG {
            get {
                return ResourceManager.GetString("EMAIL_KHONGBITRUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GENERAL_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ hồ sơ thành công..
        /// </summary>
        public static string HUYHOSO_THANHCONG {
            get {
                return ResourceManager.GetString("HUYHOSO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ hồ sơ thất bại..
        /// </summary>
        public static string HUYHOSO_THATBAI {
            get {
                return ResourceManager.GetString("HUYHOSO_THATBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra. Không thể cập nhật ảnh đại diện..
        /// </summary>
        public static string KHONGCAPNHAT_HINHDAIDIEN {
            get {
                return ResourceManager.GetString("KHONGCAPNHAT_HINHDAIDIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên {0} đã tồn tại. Vui lòng nhập mã khác..
        /// </summary>
        public static string MANVDATONTAI {
            get {
                return ResourceManager.GetString("MANVDATONTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hồ sơ không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_CHUYENHOSO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_CHUYENHOSO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hồ sơ thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_CHUYENHOSO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_CHUYENHOSO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin hồ sơ vụ án không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_HOSOVUAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_HOSOVUAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin hồ sơ vụ án thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_HOSOVUAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_HOSOVUAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nội dung mở phiên họp thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_MOPHIENHOP_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_MOPHIENHOP_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nội dung triệu tập thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_NOIDUNGTRIEUTAP_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_NOIDUNGTRIEUTAP_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nội dung đưa vụ án ra xét xử thành công..
        /// </summary>
        public static string MESSAGE_CAPNHAT_NOIDUNGXETXU_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHAT_NOIDUNGXETXU_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật án phí/ lệ phí không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATANPHI_LEPHI_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATANPHI_LEPHI_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật án phí/ lệ phí thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATANPHI_LEPHI_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATANPHI_LEPHI_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chức năng nhân viên thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATCHUCNANG_NHANVIEN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATCHUCNANG_NHANVIEN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGCAO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGCAO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo quá hạn không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGCAO_QUAHAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGCAO_QUAHAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo quá hạn  thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGCAO_QUAHAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGCAO_QUAHAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGCAO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGCAO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng nghị không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGNGHI_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGNGHI_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng nghị thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATKHANGNGHI_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATKHANGNGHI_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nộp tạm ứng án phí/ lệ phí không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATNOPTAMUNG_ANPHILETHI_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATNOPTAMUNG_ANPHILETHI_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nộp tạm ứng án phí/ lệ phí thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATNOPTAMUNG_ANPHILETHI_THANHCONG1 {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATNOPTAMUNG_ANPHILETHI_THANHCONG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin tài khoản không thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATTHONGTINTAIKHOAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATTHONGTINTAIKHOAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATTHONGTINTAIKHOAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATTHONGTINTAIKHOAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trả lại đơn kháng cáo thành công..
        /// </summary>
        public static string MESSAGE_CAPNHATTRALAIDON_KHANGCAO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_CAPNHATTRALAIDON_KHANGCAO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin lưu kho không thành công..
        /// </summary>
        public static string MESSAGE_LUUKHO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_LUUKHO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin  lưu kho thành công..
        /// </summary>
        public static string MESSAGE_LUUKHO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_LUUKHO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin  phân công thẩm phán không thành công..
        /// </summary>
        public static string MESSAGE_PHANCONGTHAMPHAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_PHANCONGTHAMPHAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin phân công thẩm phán thành công..
        /// </summary>
        public static string MESSAGE_PHANCONGTHAMPHAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_PHANCONGTHAMPHAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin phát hành bản án / quyết định không thành công..
        /// </summary>
        public static string MESSAGE_PHATHANHBANAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_PHATHANHBANAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin phát hành bản án / quyết định thành công..
        /// </summary>
        public static string MESSAGE_PHATHANHBANAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_PHATHANHBANAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Sửa chữa bổ sung bản án không thành công..
        /// </summary>
        public static string MESSAGE_SUACHUABANAN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUACHUABANAN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Sửa chữa bổ sung bản án thành công..
        /// </summary>
        public static string MESSAGE_SUACHUABANAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUACHUABANAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chức danh, chức vụ thành công.
        /// </summary>
        public static string MESSAGE_SUACHUCDANH_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUACHUCDANH_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật truy cập nhân viên tòa án thành công..
        /// </summary>
        public static string MESSAGE_SUADOITRUYCAP_TOAAN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUADOITRUYCAP_TOAAN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo không thành công..
        /// </summary>
        public static string MESSAGE_SUAKHANGCAO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUAKHANGCAO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin kháng cáo thành công..
        /// </summary>
        public static string MESSAGE_SUAKHANGCAO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUAKHANGCAO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thông tin nhân viên không thành công..
        /// </summary>
        public static string MESSAGE_SUANHANVIEN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUANHANVIEN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thông tin nhân viên thành công..
        /// </summary>
        public static string MESSAGE_SUANHANVIEN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_SUANHANVIEN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chức danh, chức vụ thành công..
        /// </summary>
        public static string MESSAGE_THEMCHUCDANH_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_THEMCHUCDANH_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thành công..
        /// </summary>
        public static string MESSAGE_THEMNHANVIEN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_THEMNHANVIEN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên từ file thành công..
        /// </summary>
        public static string MESSAGE_THEMNHANVIEN_TUFILE_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_THEMNHANVIEN_TUFILE_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thụ lý thành công..
        /// </summary>
        public static string MESSAGE_THULY_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_THULY_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin chức danh, chức vụ không thành công..
        /// </summary>
        public static string MESSAGE_XOACHUCDANH_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOACHUCDANH_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin chức danh, chức vụ thành công..
        /// </summary>
        public static string MESSAGE_XOACHUCDANH_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOACHUCDANH_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kháng cáo không thành công..
        /// </summary>
        public static string MESSAGE_XOAKHANGCAO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOAKHANGCAO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kháng cáo thành công..
        /// </summary>
        public static string MESSAGE_XOAKHANGCAO_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOAKHANGCAO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên không thành công..
        /// </summary>
        public static string MESSAGE_XOANHANVIEN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOANHANVIEN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công..
        /// </summary>
        public static string MESSAGE_XOANHANVIEN_THANHCONG {
            get {
                return ResourceManager.GetString("MESSAGE_XOANHANVIEN_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PLEASE_SELECT_ACTION {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PLEASE_SELECT_CONTROLLER {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PLEASE_SELECT_USER {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa huỷ hồ sơ thành công..
        /// </summary>
        public static string SUA_HUYHOSO_THANHCONG {
            get {
                return ResourceManager.GetString("SUA_HUYHOSO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa huỷ hồ sơ thất bại..
        /// </summary>
        public static string SUA_HUYHOSO_THATBAI {
            get {
                return ResourceManager.GetString("SUA_HUYHOSO_THATBAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string THEM_THANHCONG {
            get {
                return ResourceManager.GetString("THEM_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Nhân Viên từ file không thành công. Xin vui lòng thử lại!.
        /// </summary>
        public static string THEMNHANVIEN_TU_FILE_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THEMNHANVIEN_TU_FILE_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên từ file thành công..
        /// </summary>
        public static string THEMNHANVIEN_TU_FILE_THANHCONG {
            get {
                return ResourceManager.GetString("THEMNHANVIEN_TU_FILE_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn đương sự..
        /// </summary>
        public static string THONGBAO_BANCHUACHON_DUONGSU {
            get {
                return ResourceManager.GetString("THONGBAO_BANCHUACHON_DUONGSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhận hồ sơ không thành công..
        /// </summary>
        public static string THONGBAO_CAPNHAT_HOSO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_CAPNHAT_HOSO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhận hồ sơ thành công..
        /// </summary>
        public static string THONGBAO_CAPNHAT_HOSO_THANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_CAPNHAT_HOSO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thư ký / thẩm tra viên thành công..
        /// </summary>
        public static string THONGBAO_CAPNHAT_THUKY {
            get {
                return ResourceManager.GetString("THONGBAO_CAPNHAT_THUKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật chức danh, chức vụ không thành công..
        /// </summary>
        public static string THONGBAO_CAPNHATCHUCDANH_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_CAPNHATCHUCDANH_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại. Vui lòng sử dụng email khác..
        /// </summary>
        public static string THONGBAO_EMAIL_DATONTAI {
            get {
                return ResourceManager.GetString("THONGBAO_EMAIL_DATONTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được chức năng..
        /// </summary>
        public static string THONGBAO_KHONGCAPNHAT_CHUCNANG {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGCAPNHAT_CHUCNANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật hình đại diện..
        /// </summary>
        public static string THONGBAO_KHONGCAPNHAT_HINHDAIDIEN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGCAPNHAT_HINHDAIDIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không cập nhật được thư ký / thẩm tra viên..
        /// </summary>
        public static string THONGBAO_KHONGCAPNHAT_THUKY {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGCAPNHAT_THUKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có mẫu in..
        /// </summary>
        public static string THONGBAO_KHONGCO_MAUIN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGCO_MAUIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không lọc được dữ liệu..
        /// </summary>
        public static string THONGBAO_KHONGLOCDUOCDULIEU {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGLOCDUOCDULIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không lưu được thay đổi của nhóm án..
        /// </summary>
        public static string THONGBAO_KHONGLUU_NHOMAN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGLUU_NHOMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa nhân viên..
        /// </summary>
        public static string THONGBAO_KHONGSUA_NHANVIEN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGSUA_NHANVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin thẩm phán..
        /// </summary>
        public static string THONGBAO_KHONGSUA_THONGTIN_THAMPHAN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGSUA_THONGTIN_THAMPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thành công..
        /// </summary>
        public static string THONGBAO_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kháng cáo..
        /// </summary>
        public static string THONGBAO_KHONGTHE_KHANGCAO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHE_KHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kháng nghị..
        /// </summary>
        public static string THONGBAO_KHONGTHE_KHANGNGHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHE_KHANGNGHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lưu kho..
        /// </summary>
        public static string THONGBAO_KHONGTHE_LUUKHO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHE_LUUKHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể phát hành bản án..
        /// </summary>
        public static string THONGBAO_KHONGTHE_PHATHANH_BANAN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHE_PHATHANH_BANAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa chữa bản án..
        /// </summary>
        public static string THONGBAO_KHONGTHE_SUACHUABANAN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHE_SUACHUABANAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thêm được phân công!.
        /// </summary>
        public static string THONGBAO_KHONGTHEM_PHANCONG {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHEM_PHANCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_ANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_ANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa kết quả nộp tạm ứng án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_KETQUA_NOPTAMUNGANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_KETQUA_NOPTAMUNGANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa kết quả nộp án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_KETQUANOP_ANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_KETQUANOP_ANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa kháng cáo..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_KHANGCAO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_KHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa nộp tạm ứng án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_NOPTAMUNG_ANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_NOPTAMUNG_ANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa nộp tạm ứng án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_NOPTAMUNGANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_NOPTAMUNGANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin chuyển đơn..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_THONGTIN_CHUYENDON {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_THONGTIN_CHUYENDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin chuyển chuyển hồ sơ..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_THONGTIN_CHUYENHOSO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_THONGTIN_CHUYENHOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin hồ sơ..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_THONGTIN_HOSO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_THONGTIN_HOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin tài khoản..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_THONGTIN_TAIKHOAN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_THONGTIN_TAIKHOAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin thụ lý..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_THONGTIN_THULY {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_THONGTIN_THULY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa yêu cầu dự nộp nộp tạm ứng án phí/ lệ phí..
        /// </summary>
        public static string THONGBAO_KHONGTHESUA_YEUCAUDUNOP_TAMUNGANPHI_LEPHI {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHESUA_YEUCAUDUNOP_TAMUNGANPHI_LEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa kháng cáo..
        /// </summary>
        public static string THONGBAO_KHONGTHEXOA_KHANGCAO {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGTHEXOA_KHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa đương sự..
        /// </summary>
        public static string THONGBAO_KHONGXOA_DUONGSU {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGXOA_DUONGSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không xóa được thông tin nhân viên..
        /// </summary>
        public static string THONGBAO_KHONGXOA_NHANVIEN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGXOA_NHANVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xoá được phân công!.
        /// </summary>
        public static string THONGBAO_KHONGXOA_PHANCONG {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGXOA_PHANCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xóa được chức danh, chức vụ..
        /// </summary>
        public static string THONGBAO_KHONGXOADUOC_CHUCDANH {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGXOADUOC_CHUCDANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc dữ liệu thành công..
        /// </summary>
        public static string THONGBAO_LOCDULIEUTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_LOCDULIEUTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string THONGBAO_LOI {
            get {
                return ResourceManager.GetString("THONGBAO_LOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa thông tin chuyển hồ sơ..
        /// </summary>
        public static string THONGBAO_SUATHONGTIN_HOSO {
            get {
                return ResourceManager.GetString("THONGBAO_SUATHONGTIN_HOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đang ở trạng thái &quot;Không hoạt động&quot;, vui lòng liên hệ quản trị!.
        /// </summary>
        public static string THONGBAO_TAIKHOANKHONGHOATDONG {
            get {
                return ResourceManager.GetString("THONGBAO_TAIKHOANKHONGHOATDONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo tạm ứng án phí phúc thẩm.
        /// </summary>
        public static string THONGBAO_TAMUNGANPHI_PHUCTHAM {
            get {
                return ResourceManager.GetString("THONGBAO_TAMUNGANPHI_PHUCTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo tạm ứng lệ phí phúc thẩm.
        /// </summary>
        public static string THONGBAO_TAMUNGLEPHI_PHUCTHAM {
            get {
                return ResourceManager.GetString("THONGBAO_TAMUNGLEPHI_PHUCTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức danh, chức vụ đã tồn tại..
        /// </summary>
        public static string THONGBAO_TENCHUCDANH_KHONGTONTAI {
            get {
                return ResourceManager.GetString("THONGBAO_TENCHUCDANH_KHONGTONTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} thành công..
        /// </summary>
        public static string THONGBAO_THANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_THANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm chức danh, chức vụ không thành công..
        /// </summary>
        public static string THONGBAO_THEMCHUCDANH_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_THEMCHUCDANH_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên không thành công..
        /// </summary>
        public static string THONGBAO_THEMNHANVIEN_KHONGTHANHCONG {
            get {
                return ResourceManager.GetString("THONGBAO_THEMNHANVIEN_KHONGTHANHCONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhấp vào đây để cập nhật hình đại diện.
        /// </summary>
        public static string TITLE_NHANVAO_THAYDOI_HINHDAIDIEN {
            get {
                return ResourceManager.GetString("TITLE_NHANVAO_THAYDOI_HINHDAIDIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UPDATE_STATUS_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_STATUS_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đính kèm File bản án trước khi thực hiện thao tác này..
        /// </summary>
        public static string WARNING_DINHKEMFILE_BANAN {
            get {
                return ResourceManager.GetString("WARNING_DINHKEMFILE_BANAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đính kèm File quyết định trước khi thực hiện thao tác này..
        /// </summary>
        public static string WARNING_DINHKEMFILE_QUYETDINH {
            get {
                return ResourceManager.GetString("WARNING_DINHKEMFILE_QUYETDINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thêm dữ liệu quyết định hoặc bản án trước khi thực hiện thao tác này..
        /// </summary>
        public static string WARNING_DINHKEMFILE_QUYETDINHVABANAN {
            get {
                return ResourceManager.GetString("WARNING_DINHKEMFILE_QUYETDINHVABANAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] không tồn tại..
        /// </summary>
        public static string WARNING_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("WARNING_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning] &lt;br/&gt;&lt;br/&gt; Sheet [{0}] - Cột không đúng định dạng hoặc không có dữ liệu..
        /// </summary>
        public static string WARNING_IMPORT_FILE_NOT_VALID {
            get {
                return ResourceManager.GetString("WARNING_IMPORT_FILE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning] &lt;br/&gt;&lt;br/&gt; Sheet [{0}] - {1}.
        /// </summary>
        public static string WARNING_IMPORT_SHEET {
            get {
                return ResourceManager.GetString("WARNING_IMPORT_SHEET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin Án phí/ Lệ phí trước khi thực hiện thao tác này..
        /// </summary>
        public static string WARNING_NHAP_ANPHI {
            get {
                return ResourceManager.GetString("WARNING_NHAP_ANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng số bản án..
        /// </summary>
        public static string WARNING_TRUNG_SOBANAN {
            get {
                return ResourceManager.GetString("WARNING_TRUNG_SOBANAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng số quyết định..
        /// </summary>
        public static string WARNING_TRUNG_SOQUYETDINH {
            get {
                return ResourceManager.GetString("WARNING_TRUNG_SOQUYETDINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ bị huỷ không thể khôi phục, bạn  có chắc chắn muốn huỷ hồ sơ [ {0} ]?.
        /// </summary>
        public static string XACNHANHUYHOSO {
            get {
                return ResourceManager.GetString("XACNHANHUYHOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} đã xóa thành công..
        /// </summary>
        public static string XOA_THANHCONG {
            get {
                return ResourceManager.GetString("XOA_THANHCONG", resourceCulture);
            }
        }
    }
}
