//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.TACM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Setting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.TACM.Resources.Resources.Setting", typeof(Setting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Thanh Hùng.
        /// </summary>
        public static string CHANH_AN_TINH {
            get {
                return ResourceManager.GetString("CHANH_AN_TINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chánh Án.
        /// </summary>
        public static string CHUCDANH_CHANHAN {
            get {
                return ResourceManager.GetString("CHUCDANH_CHANHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội Thẩm Nhân Dân.
        /// </summary>
        public static string CHUCDANH_HOITHAMNHANDAN {
            get {
                return ResourceManager.GetString("CHUCDANH_HOITHAMNHANDAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm Sát Viên.
        /// </summary>
        public static string CHUCDANH_KIEMSATVIEN {
            get {
                return ResourceManager.GetString("CHUCDANH_KIEMSATVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẩm Phán.
        /// </summary>
        public static string CHUCDANH_THAMPHAN {
            get {
                return ResourceManager.GetString("CHUCDANH_THAMPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư Ký.
        /// </summary>
        public static string CHUCDANH_THUKY {
            get {
                return ResourceManager.GetString("CHUCDANH_THUKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký Xác Nhận Đã Nhận Đơn.
        /// </summary>
        public static string CHUCNANG_KYXACNHAN_NHANDON {
            get {
                return ResourceManager.GetString("CHUCNANG_KYXACNHAN_NHANDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận Biên Lai.
        /// </summary>
        public static string CHUCNANG_NHANBIENLAI {
            get {
                return ResourceManager.GetString("CHUCNANG_NHANBIENLAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/tacm/ChuKyChanhAn_HTH.png.
        /// </summary>
        public static string CHUKY_CHANH_AN_TINH {
            get {
                return ResourceManager.GetString("CHUKY_CHANH_AN_TINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Chọn--.
        /// </summary>
        public static string DDL_CHOOSE {
            get {
                return ResourceManager.GetString("DDL_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Tất cả--.
        /// </summary>
        public static string DDL_TATCA {
            get {
                return ResourceManager.GetString("DDL_TATCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có người đủ 18 tuổi trở lên xúi giục.
        /// </summary>
        public static string DDNT_BICAO_NGUOIDU18XUIGIUC {
            get {
                return ResourceManager.GetString("DDNT_BICAO_NGUOIDU18XUIGIUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_default_white.png.
        /// </summary>
        public static string DEFAULT_ICON_WHITE {
            get {
                return ResourceManager.GetString("DEFAULT_ICON_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_default.png.
        /// </summary>
        public static string DEFAULT_IMAGE_200x200 {
            get {
                return ResourceManager.GetString("DEFAULT_IMAGE_200x200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_default_large.png.
        /// </summary>
        public static string DEFAULT_IMAGE_LARGE {
            get {
                return ResourceManager.GetString("DEFAULT_IMAGE_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar_default_small.png.
        /// </summary>
        public static string DEFAULT_IMAGE_SMALL {
            get {
                return ResourceManager.GetString("DEFAULT_IMAGE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DINHDANG_NGAY {
            get {
                return ResourceManager.GetString("DINHDANG_NGAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd/MM/yyyy HH:mm:ss}.
        /// </summary>
        public static string DINHDANG_NGAY_DANHSACHNGAYSUADOI {
            get {
                return ResourceManager.GetString("DINHDANG_NGAY_DANHSACHNGAYSUADOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DINHDANG_NGAYGIO {
            get {
                return ResourceManager.GetString("DINHDANG_NGAYGIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.000.
        /// </summary>
        public static string DS_TAMUNGANPHI_GIATRIDUNOP {
            get {
                return ResourceManager.GetString("DS_TAMUNGANPHI_GIATRIDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string DS_TAMUNGANPHI_PHANTRAMDUNOP {
            get {
                return ResourceManager.GetString("DS_TAMUNGANPHI_PHANTRAMDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.000.
        /// </summary>
        public static string DS_TAMUNGANPHI_TONGANPHI {
            get {
                return ResourceManager.GetString("DS_TAMUNGANPHI_TONGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng tối đa 5MB.
        /// </summary>
        public static string DUNGLUONGTOIDA {
            get {
                return ResourceManager.GetString("DUNGLUONGTOIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cá nhân.
        /// </summary>
        public static string DUONGSULA_CANHAN {
            get {
                return ResourceManager.GetString("DUONGSULA_CANHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ quan, tổ chức.
        /// </summary>
        public static string DUONGSULA_TOCHUC {
            get {
                return ResourceManager.GetString("DUONGSULA_TOCHUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads/NhanVienImages/{0}.
        /// </summary>
        public static string EMPLOYEE_IMAGE_FOLDER {
            get {
                return ResourceManager.GetString("EMPLOYEE_IMAGE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        public static string ENCRYPT_SECRET_STRING {
            get {
                return ResourceManager.GetString("ENCRYPT_SECRET_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ hỗ trợ file *.PDF, *.DOC, *.DOCX.
        /// </summary>
        public static string FILEHOTRO {
            get {
                return ResourceManager.GetString("FILEHOTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/tacm/SlideShow/.
        /// </summary>
        public static string FOLDER_SLIDESHOW_TOAANCAMAU {
            get {
                return ResourceManager.GetString("FOLDER_SLIDESHOW_TOAANCAMAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads/Templates/.
        /// </summary>
        public static string FOLDER_TEMPLATES {
            get {
                return ResourceManager.GetString("FOLDER_TEMPLATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n0}.
        /// </summary>
        public static string FORMAT_NUMBER_THOUSANDS {
            get {
                return ResourceManager.GetString("FORMAT_NUMBER_THOUSANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.000.
        /// </summary>
        public static string HC_ANPHI_GIATRIDUNOP {
            get {
                return ResourceManager.GetString("HC_ANPHI_GIATRIDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string HC_ANPHI_PHANTRAMDUNOP {
            get {
                return ResourceManager.GetString("HC_ANPHI_PHANTRAMDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.000.
        /// </summary>
        public static string HC_ANPHI_TONGANPHI {
            get {
                return ResourceManager.GetString("HC_ANPHI_TONGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ đủ 14 đến dưới 16 tuổi.
        /// </summary>
        public static string HS_DACDIEMNHANTHANBICAO_1416 {
            get {
                return ResourceManager.GetString("HS_DACDIEMNHANTHANBICAO_1416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ đủ 16 đến dưới 18 tuổi.
        /// </summary>
        public static string HS_DACDIEMNHANTHANBICAO_1618 {
            get {
                return ResourceManager.GetString("HS_DACDIEMNHANTHANBICAO_1618", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cán bộ, công chức.
        /// </summary>
        public static string HS_DACDIEMNHANTHANBICAO_CANBO {
            get {
                return ResourceManager.GetString("HS_DACDIEMNHANTHANBICAO_CANBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đảng viên.
        /// </summary>
        public static string HS_DACDIEMNHANTHANBICAO_DANGVIEN {
            get {
                return ResourceManager.GetString("HS_DACDIEMNHANTHANBICAO_DANGVIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không phải luật sư.
        /// </summary>
        public static string HS_NGUOIBAOCHUALA_KHONGPHAILUATSU {
            get {
                return ResourceManager.GetString("HS_NGUOIBAOCHUALA_KHONGPHAILUATSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luật sư.
        /// </summary>
        public static string HS_NGUOIBAOCHUALA_LUATSU {
            get {
                return ResourceManager.GetString("HS_NGUOIBAOCHUALA_LUATSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chấp hành bản án khác.
        /// </summary>
        public static string HS_TINHTRANGGIAMGIU_CHAPHANHBANANKHAC {
            get {
                return ResourceManager.GetString("HS_TINHTRANGGIAMGIU_CHAPHANHBANANKHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tại ngoại.
        /// </summary>
        public static string HS_TINHTRANGGIAMGIU_TAINGOAI {
            get {
                return ResourceManager.GetString("HS_TINHTRANGGIAMGIU_TAINGOAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tạm giam.
        /// </summary>
        public static string HS_TINHTRANGGIAMGIU_TAMGIAM {
            get {
                return ResourceManager.GetString("HS_TINHTRANGGIAMGIU_TAMGIAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tạm giam trong vụ án khác.
        /// </summary>
        public static string HS_TINHTRANGGIAMGIU_TAMGIAMVUANKHAC {
            get {
                return ResourceManager.GetString("HS_TINHTRANGGIAMGIU_TAMGIAMVUANKHAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị can.
        /// </summary>
        public static string HS_TUCACHTOTUNG_BICAN {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_BICAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị cáo.
        /// </summary>
        public static string HS_TUCACHTOTUNG_BICAO {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_BICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị đơn dân sự.
        /// </summary>
        public static string HS_TUCACHTOTUNG_BIDON {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_BIDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bị hại.
        /// </summary>
        public static string HS_TUCACHTOTUNG_BIHAI {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_BIHAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bào chữa.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIBAOCHUA {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIBAOCHUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bảo vệ quyền và lợi ích hợp pháp.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIBAOVEQUYENLOIICH {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIBAOVEQUYENLOIICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đại diện hợp pháp của người tham gia tố tụng.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIDAIDIEN {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIDAIDIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dịch thuật.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIDICHTHUAT {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIDICHTHUAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người định giá tài sản.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIDINHGIA {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIDINHGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người giám định.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIGIAMDINH {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIGIAMDINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người làm chứng.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOILAMCHUNG {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOILAMCHUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người có quyền lợi, nghĩa vụ liên quan đến vụ án.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOILIENQUAN {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOILIENQUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người phiên dịch.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUOIPHIENDICH {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUOIPHIENDICH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên đơn dân sự.
        /// </summary>
        public static string HS_TUCACHTOTUNG_NGUYENDON {
            get {
                return ResourceManager.GetString("HS_TUCACHTOTUNG_NGUYENDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/Images/Icons/{0}.png.
        /// </summary>
        public static string ICON_HOME {
            get {
                return ResourceManager.GetString("ICON_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000.000.
        /// </summary>
        public static string KT_TAMUNGANPHI_GIATRIDUNOP {
            get {
                return ResourceManager.GetString("KT_TAMUNGANPHI_GIATRIDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string KT_TAMUNGANPHI_PHANTRAMDUNOP {
            get {
                return ResourceManager.GetString("KT_TAMUNGANPHI_PHANTRAMDUNOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.000.000.
        /// </summary>
        public static string KT_TAMUNGANPHI_TONGANPHI {
            get {
                return ResourceManager.GetString("KT_TAMUNGANPHI_TONGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranh chấp.
        /// </summary>
        public static string LOAIQUANHE_TRANHCHAP {
            get {
                return ResourceManager.GetString("LOAIQUANHE_TRANHCHAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu.
        /// </summary>
        public static string LOAIQUANHE_YEUCAU {
            get {
                return ResourceManager.GetString("LOAIQUANHE_YEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string MANHOMAN_APDUNG_BPXLHC {
            get {
                return ResourceManager.GetString("MANHOMAN_APDUNG_BPXLHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        public static string MANHOMAN_DANSU {
            get {
                return ResourceManager.GetString("MANHOMAN_DANSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HC.
        /// </summary>
        public static string MANHOMAN_HANHCHINH {
            get {
                return ResourceManager.GetString("MANHOMAN_HANHCHINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HS.
        /// </summary>
        public static string MANHOMAN_HINHSU {
            get {
                return ResourceManager.GetString("MANHOMAN_HINHSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        public static string MANHOMAN_HONNHAN {
            get {
                return ResourceManager.GetString("MANHOMAN_HONNHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KT.
        /// </summary>
        public static string MANHOMAN_KINHTE {
            get {
                return ResourceManager.GetString("MANHOMAN_KINHTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LD.
        /// </summary>
        public static string MANHOMAN_LAODONG {
            get {
                return ResourceManager.GetString("MANHOMAN_LAODONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu {0} :.
        /// </summary>
        public static string MAU {
            get {
                return ResourceManager.GetString("MAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/FileManagement/MauIn/{0}/{1}.
        /// </summary>
        public static string MAU_IN {
            get {
                return ResourceManager.GetString("MAU_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/FileManagement/MauInDoc/{0}/{1}.
        /// </summary>
        public static string MAU_IN_DOC {
            get {
                return ResourceManager.GetString("MAU_IN_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/Images/Icons/{0}.
        /// </summary>
        public static string NHANVIEN_HINH_TACM {
            get {
                return ResourceManager.GetString("NHANVIEN_HINH_TACM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads/ImportNhanVien/{0}/{1}/{2}.
        /// </summary>
        public static string NHANVIEN_IMPORT_NHANVIEN_FILE_FOLDER {
            get {
                return ResourceManager.GetString("NHANVIEN_IMPORT_NHANVIEN_FILE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import_NhanVien_{0}.xlsx.
        /// </summary>
        public static string NHANVIEN_IMPORT_NHANVIEN_FILE_NAME {
            get {
                return ResourceManager.GetString("NHANVIEN_IMPORT_NHANVIEN_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gia hạn thời hạn chuẩn bị xét xử.
        /// </summary>
        public static string QUYETDINH_GIAHANTHOIHAN {
            get {
                return ResourceManager.GetString("QUYETDINH_GIAHANTHOIHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SOLAN_DANGNHAP_SAI {
            get {
                return ResourceManager.GetString("SOLAN_DANGNHAP_SAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TACM System.
        /// </summary>
        public static string TACM_SYSTEM {
            get {
                return ResourceManager.GetString("TACM_SYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_BIAHOSOPHUCTHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_BIAHOSOPHUCTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Bia ho so so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_BIAHOSOSOTHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_BIAHOSOSOTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Giay trieu tap duong su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_GIAYTRIEUTAP {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_GIAYTRIEUTAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Quyet dinh phan cong Tham phan giai quyet khieu nai kien nghi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QDPHANCONGTHAMPHAN_PT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QDPHANCONGTHAMPHAN_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Quyet dinh phan cong Tham phan giai quyet ho so de nghi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QDPHANCONGTHAMPHAN_ST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QDPHANCONGTHAMPHAN_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 05-AD Quyet dinh dinh chi xem xet quyet dinh ADBPXLHC.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QUYETDINHDINHCHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QUYETDINHDINHCHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-AD Quyet dinh mo phien hop xem xet khieu nai kien nghi khang nghi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QUYETDINHMOPHIENHOP_PT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QUYETDINHMOPHIENHOP_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 03-AD Quyet dinh mo phien hop, xem xet, quyet dinh ADBPXLHC.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QUYETDINHMOPHIENHOP_ST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QUYETDINHMOPHIENHOP_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 06-AD Quyet dinh tam dinh chi xem xet quyet dinh ADBPXLHC.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_QUYETDINHTAMDINHCHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_QUYETDINHTAMDINHCHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 01-AD Thong bao ve viec thu ly ho so de nghi xem xet quyet dinh.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_AD_SOTHAM_THONGBAOTHULY_ST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_AD_SOTHAM_THONGBAOTHULY_ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 16-Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_BIAHOSOPHUCTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_BIAHOSOPHUCTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 16-Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_BIAHOSOPHUCTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_BIAHOSOPHUCTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 07-Bia ho so vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_BIAHOSOSOTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_BIAHOSOSOTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 06-Bia ho so vu viec so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_BIAHOSOSOTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_BIAHOSOSOTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 15-Giay trieu tap phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_PT_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_PT_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 09-Giay trieu tap so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 09-Giay trieu tap so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 15-Giay trieu tap phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_YC_PT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_GIAYTRIEUTAP_YC_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 14-QD dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_PHUCTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_PHUCTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 14- QD Mo phien hop phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_PHUCTHAM_QDMOPHIENHOP {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_PHUCTHAM_QDMOPHIENHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 14A-QD mo phien hop phuc tham xem xet QD bi khang cao khang nghi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_PHUCTHAM_QDMOPHIENHOP_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_PHUCTHAM_QDMOPHIENHOP_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 12-Thong bao thu ly phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_PHUCTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_PHUCTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 12-Thong bao thu ly phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_PHUCTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_PHUCTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 13-QD phan cong phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QDPHANCONGTHAMPHANGIAIQUYETVUANPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QDPHANCONGTHAMPHANGIAIQUYETVUANPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 13-QD phan cong giai quyet phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QDPHANCONGTHAMPHANGIAIQUYETVUVIECPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QDPHANCONGTHAMPHANGIAIQUYETVUVIECPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 08-QD dua vu an ra xet xu.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QUYETDINHDUAVUANRAXETXUST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QUYETDINHDUAVUANRAXETXUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 08-QD mo phien hop so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QUYETDINHMOPHIENHOPST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QUYETDINHMOPHIENHOPST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 06-QD Phan cong giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 07-QD Phan cong Tham phan so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUVIECST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUVIECST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 01-Bia ho so khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_BIAHOSONHANDON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_BIAHOSONHANDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 01-Bia ho so yeu cau.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_BIAHOSONHANDON_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_BIAHOSONHANDON_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 02-Giay xac nhan đa nhan don khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 02-Giay xac nhan da nhan don yeu cau.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_GIAYXACNHANDANHANDONYEUCAU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_GIAYXACNHANDANHANDONYEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 03-QD Phan cong giai quyet don khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 03-QD phan cong giai quyet don.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 04-Thong bao nop tien tam ung an phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGANPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 11-Thong bao nop tien tam ung an phi phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGANPHIPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGANPHIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 04-Thong bao nop tien tam ung le phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGLEPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGLEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 11-Thong bao nop tien tam ung le phi phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGLEPHIPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTAMUNGLEPHIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 05-Thong bao ve viec thu ly vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 05-Thong bao thu ly viec dan su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-TC-Mau so 10-Giay xac nhan da nhan đon khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_XACNHANDANHANDONKHANGCAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_XACNHANDANHANDONKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS-YC-Mau so 10-Giay xac nhan da nhan don khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_DS_SOTHAM_XACNHANDANHANDONKHANGCAO_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_DS_SOTHAM_XACNHANDANHANDONKHANGCAO_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Giay trieu tap duong su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_GIAYTRIEUTAP {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_GIAYTRIEUTAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_PHUCTHAM_BIAHOSO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_PHUCTHAM_BIAHOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 36 HC-Quyet dinh dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_PHUCTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_PHUCTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 37 HC-Quyet dinh dua vu an ra xet xu phuc tham theo thu tuc rut gon.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_PHUCTHAM_QDDUAVUANRAXETXURUTGON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_PHUCTHAM_QDDUAVUANRAXETXURUTGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 35 HC-Thong bao ve viec thu ly vu an de xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_PHUCTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_PHUCTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Quyet dinh phan cong Tham phan giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_QUYETDINHPHANCONGTHAMPHAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_QUYETDINHPHANCONGTHAMPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Quyet dinh phan cong Tham phan, Hoi tham giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_QUYETDINHPHANCONGTHAMPHANHOITHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_QUYETDINHPHANCONGTHAMPHANHOITHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Bia ho so so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_BIAHOSO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_BIAHOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HC-Bia ho so nhan don.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_BIAHOSONHANDON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_BIAHOSONHANDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 02 HC-Giay xac nhan da nhan đon khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 16 HC-Quyet dinh dua vu an ra xet xu so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 17 HC-Quyet dinh dua vu an ra giai quyet so tham theo thu tuc rut gon.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_QDDUAVUANRAXETXURUTGON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_QDDUAVUANRAXETXURUTGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 04 HC-Thong bao nop tien tam ung an phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTAMUNGANPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTAMUNGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 31 HC-Thong bao nop tien tam ung an phi phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTAMUNGANPHIPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTAMUNGANPHIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 06 HC-Thong bao ve viec thu ly vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 25 HC-Giay xac nhan da nhan don khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HC_SOTHAM_XACNHANDANHANDONKHANGCAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HC_SOTHAM_XACNHANDANHANDONKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 16-Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_BIAHOSOPHUCTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_BIAHOSOPHUCTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 16-Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_BIAHOSOPHUCTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_BIAHOSOPHUCTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 07-Bia ho so vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_BIAHOSOSOTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_BIAHOSOSOTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 07-QD Phan cong Tham phan so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_BIAHOSOSOTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_BIAHOSOSOTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 09-Giay trieu tap so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_GIAYTRIEUTAP_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_GIAYTRIEUTAP_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 14-QD dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_PHUCTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_PHUCTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 14- QD Mo phien hop phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_PHUCTHAM_QDMOPHIENHOP {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_PHUCTHAM_QDMOPHIENHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 14A-QD mo phien hop phuc tham xem xet QD bi khang cao khang nghi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_PHUCTHAM_QDMOPHIENHOP_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_PHUCTHAM_QDMOPHIENHOP_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 12-Thong bao thu ly phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_PHUCTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_PHUCTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 12-Thong bao thu ly phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_PHUCTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_PHUCTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 13-QD phan cong phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QDPHANCONGTHAMPHANGIAIQUYETVUANPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QDPHANCONGTHAMPHANGIAIQUYETVUANPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 13-QD phan cong giai quyet phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QDPHANCONGTHAMPHANGIAIQUYETVUVIECPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QDPHANCONGTHAMPHANGIAIQUYETVUVIECPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 08-QD dua vu an ra xet xu.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QUYETDINHDUAVUANRAXETXUST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QUYETDINHDUAVUANRAXETXUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 08-QD mo phien hop so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QUYETDINHMOPHIENHOPST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QUYETDINHMOPHIENHOPST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 06-QD Phan cong giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 07-QD Phan cong Tham phan so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUVIECST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUVIECST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 01-Bia ho so khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_BIAHOSONHANDON {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_BIAHOSONHANDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 01-Bia ho so yeu cau.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_BIAHOSONHANDON_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_BIAHOSONHANDON_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 02-Giay xac nhan da nhan don yeu cau.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_GIAYXACNHANDANHANDONYEUCAU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_GIAYXACNHANDANHANDONYEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 03-QD phan cong giai quyet don.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_QUYETDINHPHANCONGTHAMPHANGIAIQUYETDON_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 04-Thong bao nop tien tam ung le phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTAMUNGLEPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTAMUNGLEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 05-Thong bao ve viec thu ly vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 05-Thong bao thu ly viec dan su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-TC-Mau so 10-Giay xac nhan da nhan don khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_XACNHANDANHANDONKHANGCAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_XACNHANDANHANDONKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN-YC-Mau so 10-Giay xac nhan da nhan don khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HN_SOTHAM_XACNHANDANHANDONKHANGCAO_YC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HN_SOTHAM_XACNHANDANHANDONKHANGCAO_YC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HS-Bia Ho so Hinh su phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_BIAHOSOPHUCTHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_BIAHOSOPHUCTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HS-Bia Ho so Hinh su so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_BIAHOSOSOTHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_BIAHOSOSOTHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HS-Giay trieu tap bi cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_GIAYTRIEUTAPBICAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_GIAYTRIEUTAPBICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau HS-Giay trieu tap nguoi tham gia to tung.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_GIAYTRIEUTAPNGUOITHAMGIATOTUNG {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_GIAYTRIEUTAPNGUOITHAMGIATOTUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 21 - HS Quyet dinh dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_QUYETDINHDUAVUANRAXETXUPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_QUYETDINHDUAVUANRAXETXUPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 20 - HS Quyet dinh dua vu an ra xet xu so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_QUYETDINHDUAVUANRAXETXUST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_QUYETDINHDUAVUANRAXETXUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 01 - HS Quyet dinh phan cong Hoi tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGHOITHAM {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGHOITHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 01 - HS Quyet dinh phan cong Tham phan.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGTHAMPHAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGTHAMPHAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 02 - HS Quyet dinh phan cong Thu ky.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGTHUKY {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_HS_QUYETDINHPHANCONGTHUKY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_BIAHOSOPHUCTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_BIAHOSOPHUCTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Bia ho so viec phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_BIAHOSOPHUCTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_BIAHOSOPHUCTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Bia ho so so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_BIAHOSOSOTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_BIAHOSOSOTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Bia ho so viec so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_BIAHOSOSOTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_BIAHOSOSOTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Giay trieu tap duong su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_GIAYTRIEUTAP_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_GIAYTRIEUTAP_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 66-KDTM Quyet dinh dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_PHUCTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_PHUCTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 65-KDTM Thong bao ve viec thu ly vu an de xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_PHUCTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_PHUCTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Quyet dinh phan cong Tham phan giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_QDPHANCONGTHAMPHANGIAIQUYETVUANPT {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_QDPHANCONGTHAMPHANGIAIQUYETVUANPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 47-KDTM Quyet dinh dua vu an ra xet xu so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_QUYETDINHDUAVUANRAXETXUST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_QUYETDINHDUAVUANRAXETXUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 47-KDTM Quyet dinh mo phien hop so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_QUYETDINHMOPHIENHOPST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_QUYETDINHMOPHIENHOPST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-KDTM Quyet dinh phan cong Tham phan Hoi tham giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 24-KDTM Giay xac nhan da nhan don khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 24-KDTM Giay xac nhan da nhan don yeu cau.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_GIAYXACNHANDANHANDONYEUCAU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_GIAYXACNHANDANHANDONYEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 29-KDTM Thong bao nop tien tam ung an phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTAMUNGANPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTAMUNGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 29-KDTM Thong bao nop tien tam ung le phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTAMUNGLEPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTAMUNGLEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 30-KDTM Thong bao ve viec thu ly vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 30-KDTM Thong bao ve viec thu ly viec KDTM.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 55-KDTM Giay xac nhan da nhan dnn khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_KD_SOTHAM_XACNHANDANHANDONKHANGCAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_KD_SOTHAM_XACNHANDANHANDONKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Bia ho so phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_BIAHOSOPHUCTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_BIAHOSOPHUCTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Bia ho so viec phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_BIAHOSOPHUCTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_BIAHOSOPHUCTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Bia ho so so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_BIAHOSOSOTHAM_VUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_BIAHOSOSOTHAM_VUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Bia ho so viec so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_BIAHOSOSOTHAM_VUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_BIAHOSOSOTHAM_VUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Giay trieu tap duong su.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_GIAYTRIEUTAP_TC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_GIAYTRIEUTAP_TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 66-LD Quyet dinh dua vu an ra xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_PHUCTHAM_QDDUAVUANRAXETXU {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_PHUCTHAM_QDDUAVUANRAXETXU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 65-LD Thong bao ve viec thu ly vu an de xet xu phuc tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_PHUCTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_PHUCTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 47-LD Quyet dinh dua vu an ra xet xu so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_QUYETDINHDUAVUANRAXETXUST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_QUYETDINHDUAVUANRAXETXUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 47-LD Quyet dinh mo phien hop so tham.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_QUYETDINHMOPHIENHOPST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_QUYETDINHMOPHIENHOPST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau-LD Quyet dinh phan cong Tham phan Hoi tham giai quyet vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_QUYETDINHPHANCONGTHAMPHANGIAIQUYETVUANST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 24-LD Giay xac nhan da nhan don khoi kien.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_GIAYXACNHANDANHANDONKHOIKIEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 29-LD Thong bao nop tien tam ung an phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTAMUNGANPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTAMUNGANPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 29-LD Thong bao nop tien tam ung le phi.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTAMUNGLEPHI {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTAMUNGLEPHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 30-LD Thong bao ve viec thu ly vu an.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTHULYVUAN {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTHULYVUAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 30-LD Thong bao ve viec thu ly viec LD.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTHULYVUVIEC {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_THONGBAOTHULYVUVIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau so 55-LD Giay xac nhan da nhan dnn khang cao.docx.
        /// </summary>
        public static string TEMPLATE_MAUIN_LD_SOTHAM_XACNHANDANHANDONKHANGCAO {
            get {
                return ResourceManager.GetString("TEMPLATE_MAUIN_LD_SOTHAM_XACNHANDANHANDONKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Uploads/Templates/MauInFileDoc/.
        /// </summary>
        public static string TEMPLATES_MAUIN_FOLDER {
            get {
                return ResourceManager.GetString("TEMPLATES_MAUIN_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có tệp tin nào được tải lên..
        /// </summary>
        public static string THONGBAO_KHONGCOTEP_TAILEN {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGCOTEP_TAILEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có file.
        /// </summary>
        public static string THONGBAO_KHONGFILE {
            get {
                return ResourceManager.GetString("THONGBAO_KHONGFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi:.
        /// </summary>
        public static string THONGBAOLOI {
            get {
                return ResourceManager.GetString("THONGBAOLOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi_Tien_Xet_Xu_{0}.xlsx.
        /// </summary>
        public static string THONGKE_CHITIENXETXU_FILENAME {
            get {
                return ResourceManager.GetString("THONGKE_CHITIENXETXU_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_Sach_Ho_So_{0}.xlsx.
        /// </summary>
        public static string THONGKE_DANHSACHHOSO_FILENAME {
            get {
                return ResourceManager.GetString("THONGKE_DANHSACHHOSO_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_Sach_Ho_So_Luu_Kho_{0}.xlsx.
        /// </summary>
        public static string THONGKELUUKHO_DANHSACHHOSO_FILENAME {
            get {
                return ResourceManager.GetString("THONGKELUUKHO_DANHSACHHOSO_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút gọn.
        /// </summary>
        public static string THUTUC_RUTGON {
            get {
                return ResourceManager.GetString("THUTUC_RUTGON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông thường.
        /// </summary>
        public static string THUTUC_THONGTHUONG {
            get {
                return ResourceManager.GetString("THUTUC_THONGTHUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển đơn.
        /// </summary>
        public static string TRANGTHAICONGDOAN_CHUYENDON {
            get {
                return ResourceManager.GetString("TRANGTHAICONGDOAN_CHUYENDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hồ sơ.
        /// </summary>
        public static string TRANGTHAICONGDOAN_CHUYENHOSO {
            get {
                return ResourceManager.GetString("TRANGTHAICONGDOAN_CHUYENHOSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://123.30.75.2:9969.
        /// </summary>
        public static string URL_CAUHINHHETHONG {
            get {
                return ResourceManager.GetString("URL_CAUHINHHETHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://quanlian.camau.org.vn/datlaimatkhau.
        /// </summary>
        public static string URL_DATLAIMATKHAU {
            get {
                return ResourceManager.GetString("URL_DATLAIMATKHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string VALUE_KIEMSATVIEN_KHONG {
            get {
                return ResourceManager.GetString("VALUE_KIEMSATVIEN_KHONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vắng mặt.
        /// </summary>
        public static string VALUE_KIEMSATVIEN_VANGMAT {
            get {
                return ResourceManager.GetString("VALUE_KIEMSATVIEN_VANGMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoài tỉnh.
        /// </summary>
        public static string VUNG_CHUYENHOSO_NGOAITINH {
            get {
                return ResourceManager.GetString("VUNG_CHUYENHOSO_NGOAITINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong tỉnh.
        /// </summary>
        public static string VUNG_CHUYENHOSO_TRONGTINH {
            get {
                return ResourceManager.GetString("VUNG_CHUYENHOSO_TRONGTINH", resourceCulture);
            }
        }
    }
}
