//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biz.Lib.TACM.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Biz.Lib.TACM.Resources.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chọn file!.
        /// </summary>
        public static string VALIDATION_CHUACHONFILE {
            get {
                return ResourceManager.GetString("VALIDATION_CHUACHONFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn đương sự nhận phát hành..
        /// </summary>
        public static string VALIDATION_DUONGSUPHATHANH {
            get {
                return ResourceManager.GetString("VALIDATION_DUONGSUPHATHANH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ. Vui lòng nhập lại..
        /// </summary>
        public static string VALIDATION_EMAIL_KHONGHOPLE {
            get {
                return ResourceManager.GetString("VALIDATION_EMAIL_KHONGHOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập tin tải lên vượt quá dung lượng tối đa {0}..
        /// </summary>
        public static string VALIDATION_FILE_SIZE_TOO_BIG {
            get {
                return ResourceManager.GetString("VALIDATION_FILE_SIZE_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị nhập không hợp lệ..
        /// </summary>
        public static string VALIDATION_GIATRINHAPKHONGHOPLE {
            get {
                return ResourceManager.GetString("VALIDATION_GIATRINHAPKHONGHOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm đơn không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string VALIDATION_GIOIHAN_NGAYLAMDON {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_NGAYLAMDON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm đơn nhỏ hơn hoặc bằng ngày nộp đơn tại tòa án..
        /// </summary>
        public static string VALIDATION_GIOIHAN_NGAYLAMDON_NHOHON {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_NGAYLAMDON_NHOHON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mở phiên họp phải nhỏ hơn ngày ngày ra quyết đinh..
        /// </summary>
        public static string VALIDATION_GIOIHAN_NGAYMOPHIENHOP {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_NGAYMOPHIENHOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày trả đơn không được lớn hơn ngày hiện tại..
        /// </summary>
        public static string VALIDATION_GIOIHAN_NGAYTRADON_SO_NGAYHIENTAI {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_NGAYTRADON_SO_NGAYHIENTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày yêu cầu phải không được lơn hơn ngày hiện tại..
        /// </summary>
        public static string VALIDATION_GIOIHAN_NGAYYEUCAY_SO_NGAYHIENTAI {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_NGAYYEUCAY_SO_NGAYHIENTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn sửa đổi / bổ sung đơn phải lớn hơn hoặc bằng ngày yêu cầu..
        /// </summary>
        public static string VALIDATION_GIOIHAN_THOIHANSUADOI_SO_NGAYYEUCAU {
            get {
                return ResourceManager.GetString("VALIDATION_GIOIHAN_THOIHANSUADOI_SO_NGAYYEUCAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức gửi đơn khác không được bỏ trống..
        /// </summary>
        public static string VALIDATION_GUIDONKHAC_KHONGDUOCTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_GUIDONKHAC_KHONGDUOCTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức không được để trống..
        /// </summary>
        public static string VALIDATION_HINHTHUC_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_HINHTHUC_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức nộp không được để trống..
        /// </summary>
        public static string VALIDATION_HINHTHUCNOP_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_HINHTHUCNOP_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội thẩm nhân dân không được để trống..
        /// </summary>
        public static string VALIDATION_HOITHAMNHANDAN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_HOITHAMNHANDAN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội thẩm nhân dân 2 không được để trống..
        /// </summary>
        public static string VALIDATION_HOITHAMNHANDAN2_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_HOITHAMNHANDAN2_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống..
        /// </summary>
        public static string VALIDATION_KHONGDETRONG {
            get {
                return ResourceManager.GetString("VALIDATION_KHONGDETRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không hợp lệ. Vui lòng nhập lại..
        /// </summary>
        public static string VALIDATION_KIEMTRAEMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_KIEMTRAEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới không chính xác..
        /// </summary>
        public static string VALIDATION_KIEMTRALAIMATKHAU {
            get {
                return ResourceManager.GetString("VALIDATION_KIEMTRALAIMATKHAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        public static string VALIDATION_KIEMTRARONG {
            get {
                return ResourceManager.GetString("VALIDATION_KIEMTRARONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là kiểu kí tự số..
        /// </summary>
        public static string VALIDATION_KIEMTRASO {
            get {
                return ResourceManager.GetString("VALIDATION_KIEMTRASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại quan hệ không được để trống..
        /// </summary>
        public static string VALIDATION_LOAIQUANHE_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_LOAIQUANHE_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do không được vượt quá 500 kí tự..
        /// </summary>
        public static string VALIDATION_LYDO_KHONGQUA {
            get {
                return ResourceManager.GetString("VALIDATION_LYDO_KHONGQUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do không được để trống..
        /// </summary>
        public static string VALIDATION_LYDO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_LYDO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do chuyển đơn không được để trống..
        /// </summary>
        public static string VALIDATION_LYDOCHUYENDON_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_LYDOCHUYENDON_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do chuyển hồ sơ không được để trống..
        /// </summary>
        public static string VALIDATION_LYDOCHUYENHOSO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_LYDOCHUYENHOSO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chuyển hồ sơ không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYCHUYENHOSO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYCHUYENHOSO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm đơn không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYLAMDON_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYLAMDON_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày làm đơn kháng cáo phải nhỏ hơn hoặc bằng Ngày nộp đơn kháng cáo..
        /// </summary>
        public static string VALIDATION_NGAYLAMKHANGCAO_NHOHON_NGAYNOPKHANGCAO {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYLAMKHANGCAO_NHOHON_NGAYNOPKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lưu không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYLUU_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYLUU_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYNOPDON_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYNOPDON_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nộp đơn kháng cáo phải lớn hơn hoặc bằng Ngày làm đơn kháng cáo..
        /// </summary>
        public static string VALIDATION_NGAYNOPKHANGCAO_LONHON_NGAYLAMKHANGCAO {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYNOPKHANGCAO_LONHON_NGAYLAMKHANGCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày phân công không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYPHANCONG_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYPHANCONG_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày ra phiếu chuyển không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYRAPHIEUCHUYEN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYRAPHIEUCHUYEN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sửa chữa, bổ sung không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYSUACHUA_BOSUNG_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYSUACHUA_BOSUNG_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thụ lý không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYTHULY_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYTHULY_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tòa án nhận văn bản kháng nghị không được để trống..
        /// </summary>
        public static string VALIDATION_NGAYTOAAN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGAYTOAAN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người giao không được để trống..
        /// </summary>
        public static string VALIDATION_NGUOIDAO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGUOIDAO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người kháng cáo không được để trống..
        /// </summary>
        public static string VALIDATION_NGUOIKHANGCAO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGUOIKHANGCAO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người ký không được để trống..
        /// </summary>
        public static string VALIDATION_NGUOIKY_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGUOIKY_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận lưu không được để trống..
        /// </summary>
        public static string VALIDATION_NGUOINHAN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGUOINHAN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người phân công không được để trống..
        /// </summary>
        public static string VALIDATION_NGUOIPHANCONG_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NGUOIPHANCONG_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung kháng nghị không được để trống..
        /// </summary>
        public static string VALIDATION_NOIDUNG_KHANGNGHI_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NOIDUNG_KHANGNGHI_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung yêu cầu tòa án giải quyết không được để trống..
        /// </summary>
        public static string VALIDATION_NOIDUNGGIAIQUYET_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NOIDUNGGIAIQUYET_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung kháng cáo không được để trống..
        /// </summary>
        public static string VALIDATION_NOIDUNGKHANGCAO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NOIDUNGKHANGCAO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung sửa chữa không được để trống..
        /// </summary>
        public static string VALIDATION_NOIDUNGSUACHUA_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_NOIDUNGSUACHUA_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quan hệ pháp luật không được để trống..
        /// </summary>
        public static string VALIDATION_QUANHEPHAPLUAT_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_QUANHEPHAPLUAT_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} kí tự..
        /// </summary>
        public static string VALIDATION_SOLUONGKYTUTOIDA {
            get {
                return ResourceManager.GetString("VALIDATION_SOLUONGKYTUTOIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được ít hơn {1} ký tự..
        /// </summary>
        public static string VALIDATION_SOLUONGKYTUTOITHIEU {
            get {
                return ResourceManager.GetString("VALIDATION_SOLUONGKYTUTOITHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là số nguyên dương..
        /// </summary>
        public static string VALIDATION_SONGUYENDUONG {
            get {
                return ResourceManager.GetString("VALIDATION_SONGUYENDUONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thụ lý không được để trống..
        /// </summary>
        public static string VALIDATION_SOTHULY_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_SOTHULY_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thụ lý bị trùng..
        /// </summary>
        public static string VALIDATION_SOTHULYBITRUNG {
            get {
                return ResourceManager.GetString("VALIDATION_SOTHULYBITRUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẩm phán không được để trống..
        /// </summary>
        public static string VALIDATION_THAMPHAN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THAMPHAN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẩm phán 1 không được để trống..
        /// </summary>
        public static string VALIDATION_THAMPHAN1_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THAMPHAN1_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẩm phán 2 không được để trống..
        /// </summary>
        public static string VALIDATION_THAMPHAN2_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THAMPHAN2_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn giải quyết đến ngày không được để trống..
        /// </summary>
        public static string VALIDATION_THOIGIANGIAIQUYET_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THOIGIANGIAIQUYET_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian mở phiên tòa/phiên họp phải lớn hơn ngày tháng năm ra quyết định.
        /// </summary>
        public static string VALIDATION_THOIGIANMOPHIENTOA_LONHON_RAQUYETDINH {
            get {
                return ResourceManager.GetString("VALIDATION_THOIGIANMOPHIENTOA_LONHON_RAQUYETDINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư ký không được để trống..
        /// </summary>
        public static string VALIDATION_THUKY_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THUKY_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thụ lý theo thủ tục không được để trống..
        /// </summary>
        public static string VALIDATION_THULYTHUTUC_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_THULYTHUTUC_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng kháng cáo không được để trống..
        /// </summary>
        public static string VALIDATION_TINHTRANGKHANGCAO_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_TINHTRANGKHANGCAO_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tòa án chuyển đến không được để trống..
        /// </summary>
        public static string VALIDATION_TOAANCHUYENDEN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_TOAANCHUYENDEN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} này đã tồn tại..
        /// </summary>
        public static string VALIDATION_TONTAI {
            get {
                return ResourceManager.GetString("VALIDATION_TONTAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp chuyển không được để trống..
        /// </summary>
        public static string VALIDATION_TRUONGHOPCHUYEN_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_TRUONGHOPCHUYEN_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường hợp thụ lý không được để trống..
        /// </summary>
        public static string VALIDATION_TRUONGHOPTHULY_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_TRUONGHOPTHULY_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản kháng nghị không được vượt quá 250. kí tự.
        /// </summary>
        public static string VALIDATION_VANBAN_KHANGNGHI_KHONGQUA {
            get {
                return ResourceManager.GetString("VALIDATION_VANBAN_KHANGNGHI_KHONGQUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản kháng nghị không được để trống..
        /// </summary>
        public static string VALIDATION_VANBAN_KHANGNGHI_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_VANBAN_KHANGNGHI_KHONGTRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viện kiểm sát kháng nghị không được để trống..
        /// </summary>
        public static string VALIDATION_VIENKIERMSAT_KHONGTRONG {
            get {
                return ResourceManager.GetString("VALIDATION_VIENKIERMSAT_KHONGTRONG", resourceCulture);
            }
        }
    }
}
